name: firmbox
description: "FirmBox - Twoja firma od pomysłu do realizacji"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  firebase_storage: ^12.4.6
  cloud_firestore: ^5.6.8
  firebase_app_check: ^0.3.0
  
  # Auth
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^6.1.2
  
  # HTTP & API
  http: ^1.4.0
  
  # State Management
  provider: ^6.1.5
  
  # Utilities
  file_picker: ^10.1.9
  path_provider: ^2.1.5
  pdf: ^3.11.3
  printing: ^5.14.2
  uuid: ^4.5.1
  flutter_dotenv: ^5.2.1
  url_launcher: ^6.3.1
  universal_io: ^2.2.2
  permission_handler: ^11.3.1
  dio: ^5.8.0
  gal: ^2.3.1
  
  # UI & Animations
  flutter_staggered_animations: ^1.1.1
  smooth_page_indicator: ^1.2.0
  loading_animation_widget: ^1.3.0
  flutter_svg: ^2.0.12
  google_fonts: ^6.2.1
  flutter_colorpicker: ^1.1.0
  
  # Particles Background
  particles_flutter: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/logos/
    - .env

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logos/app_icon.png"
  min_sdk_android: 23
