// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbE6yYKN4Sdgs3puVbWXA5_I2h_Jf9N0w',
    appId: '1:349018984870:web:01b1f4822df27b8ded7f67',
    messagingSenderId: '349018984870',
    projectId: 'firmbox-6dca6',
    authDomain: 'firmbox-6dca6.firebaseapp.com',
    storageBucket: 'firmbox-6dca6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnnC2U7pbF41qVJPbtU0YPFW9VfNEmNwQ',
    appId: '1:349018984870:android:9f9016357cd02f7ced7f67',
    messagingSenderId: '349018984870',
    projectId: 'firmbox-6dca6',
    storageBucket: 'firmbox-6dca6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsxRgynuW4qT9oNjfcg38fd6ECail8efc',
    appId: '1:349018984870:ios:fbe28dfc0f51170ded7f67',
    messagingSenderId: '349018984870',
    projectId: 'firmbox-6dca6',
    storageBucket: 'firmbox-6dca6.firebasestorage.app',
    iosBundleId: 'com.example.firmbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsxRgynuW4qT9oNjfcg38fd6ECail8efc',
    appId: '1:349018984870:ios:fbe28dfc0f51170ded7f67',
    messagingSenderId: '349018984870',
    projectId: 'firmbox-6dca6',
    storageBucket: 'firmbox-6dca6.firebasestorage.app',
    iosBundleId: 'com.example.firmbox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbE6yYKN4Sdgs3puVbWXA5_I2h_Jf9N0w',
    appId: '1:349018984870:web:e58535030023bf23ed7f67',
    messagingSenderId: '349018984870',
    projectId: 'firmbox-6dca6',
    authDomain: 'firmbox-6dca6.firebaseapp.com',
    storageBucket: 'firmbox-6dca6.firebasestorage.app',
  );

}